//import 'jquery'
import './js/bootstrap.min.js'
import './js/angular.min.js'
import './js/angular-route.min.js'
import './js/module.js'
import './js/controllers.js'
import './js/directives.js'
import './js/services.js'
import './js/index.js'

